### ISSUE TITLE
关于第三章lambda设置

### ISSUE THREAD

**Issue by LianZhuotao** [FederatedAI/Practicing-Federated-Learning#16]
您好，请问一下lambda什么含义，为什么取0.1？虽然一共有10个人，但参与聚合的有k人，k=5那么lambda不应为0.2吗？

**Comment by YAPDF** [comment]
您好，我也有这个疑惑，lambda为何取0.1

**Comment by LianZhuotao** [comment]
> 
你好，我想这个问题已经解决了。不要理解成传统的权重，应该理解成全局模型更新的步长。
