### ISSUE TITLE
实体书引用链接缺失

### ISSUE THREAD

**Issue by loafbaker** [FederatedAI/Practicing-Federated-Learning#3]
原书中第3、4、7、12章中多次引用了外部参考链接，如“链接3-5”、“链接7-13”，然而，在整本实体书中，并无法找到这些链接具体引用的地址。目前，对此状况并无解决方案。

**Comment by innovation-cat** [comment]
实体书受电子出版社政策限制，不能放链接，这个已经在本项目页面有说明，对应的链接已经放置在github页面：

https://github.com/FederatedAI/Practicing-Federated-Learning/blob/main/figures/link.md

**Comment by innovation-cat** [comment]
![image](https://user-images.githubusercontent.com/4070781/124223025-7ce40500-db35-11eb-8b30-cb8a72393f41.png)

**Comment by loafbaker** [comment]
> 
> 
> 实体书受电子出版社政策限制，不能放链接，这个已经在本项目页面有说明，对应的链接已经放置在github页面：
> 
> https://github.com/FederatedAI/Practicing-Federated-Learning/blob/main/figures/link.md

这个很有用，感谢！
