### ISSUE TITLE
第10章联邦视觉案例，数据集无法下载

### ISSUE THREAD

**Issue by ghl116** [FederatedAI/Practicing-Federated-Learning#9]
如题，根据readme提示，打开https://dataset.fedai.org/#/datasetfed，没有找到注册页面，无法下载数据集。希望可以把数据集上传到github，或者kaggle上面

**Comment by innovation-cat** [comment]
你好，该数据集版权属于外部合作公司，目前因为双方的合作已经结束，这个数据集不能再访问了，请使用公开数据集，后面会改一下这里把这个公开数据集删除。

谢谢。

尼古拉斯德彪 ***@***.***> 于2022年5月26日周四 11:44写道：
